### PR TITLE
add method to calculate power of a number

### PR DESCRIPTION
**Pull request by ays14**
## Related Issue 

Closes: #50 

### Describe the changes you've made

- Added a method `doPower` which accepts two arguments: `base` and `exponent` and then returns the value of `base ^ exponent`

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- By running a few test cases on local

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
Thanks for adding the documentation along with the code. 

Good job.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@ays14 There's some merge conflicts. Kindly fix it then I'll merge it.

**Comment by ays14** [comment]
> @ays14 There's some merge conflicts. Kindly fix it then I'll merge it.

Hi @Susmita-Dey , resolved the conflicts, please check.

**Review by its-abhirup — APPROVED** [review]
LGTM

**Review by Susmita-Dey — APPROVED** [review]
Great job!

**Pull request merged**
