### PR TITLE
feat: dynamic doInc and doDecr

### PR DESCRIPTION
**Pull request by rahmat-st**

### CODE REVIEW

**Comment by rahmat-st** [comment]
Hi @Susmita-Dey, can you review my PR?

**Comment by Susmita-Dey** [comment]
@rahmat-st Issue no? 

Alos, update your branch

**Comment by Susmita-Dey** [comment]
@rahmat-st update your branch

**Comment by rahmat-st** [comment]
Done

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
