### PR TITLE
refactor: change license

### PR DESCRIPTION
**Pull request by schmelto**
repo license is mit i think this here should also be mit

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for contributing. I forgot to change it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

**Comment by Susmita-Dey** [comment]
@schmelto Do you know how to change it [here](https://www.npmjs.com/package/all-round-calculator)?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by schmelto** [comment]
> @schmelto Do you know how to change it [here](https://www.npmjs.com/package/all-round-calculator)?

I think it will take the license from the package.json file so if you deploy the package again to npm it should be update the license

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Susmita-Dey** [comment]
> > @schmelto Do you know how to change it [here](https://www.npmjs.com/package/all-round-calculator)?
> 
> I think it will take the license from the package.json file so if you deploy the package again to npm it should be update the license

I used `npm publish` to deploy my package on npm. I can't use it again. Do you know any method?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Susmita-Dey** [comment]
@schmelto Is there any ISC license on GitHub? I didn't find any.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by schmelto** [comment]
> > > @schmelto Do you know how to change it [here](https://www.npmjs.com/package/all-round-calculator)?
> > 
> > 
> > I think it will take the license from the package.json file so if you deploy the package again to npm it should be update the license
> 
> I used `npm publish` to deploy my package on npm. I can't use it again. Do you know any method?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  ❓ I have a question

https://cloudfour.com/thinks/how-to-publish-an-updated-version-of-an-npm-package/

**Comment by schmelto** [comment]
> @schmelto Is there any ISC license on GitHub? I didn't find any.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  ❓ I have a question

I dont know

**Pull request merged**
