### PR TITLE
Added celsius to fahrenheit functionality

### PR DESCRIPTION
**Pull request by roshan-acharya**
-Added celsius to fahrenheit functionality

Closes: #41 

Describe the changes you've made

I have added celsius to fahrenheit functionality
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by roshan-acharya** [comment]
@Susmita-Dey fixed

**Review by its-abhirup — APPROVED** [review]
Useful function. Looks good.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Comment by Susmita-Dey** [comment]
@roshan-acharya Merge conflicts again

**Pull request merged**
